### ISSUE TITLE
Not possible to add markers on parts of the map with non-western alphabet?

### ISSUE THREAD

**Issue by sysyfo** [FacilMap/facilmap#115]
Hey,
I try to add markers on greek localities but I get an error code:
Incorrect string value: '\xCE\xA0\xCE\xAE\xCE\xBB...' for column 'name' at row 1
I have no problem when I add French localities (western alphabet) so I guess it's due to the greek characters.

(Optional wish) In general I also think it could be nice to have western alphabeth in the whole map
thanks
Ciao

sysyfo

**Comment by cdauth** [comment]
Are you using the installation on https://facilmap.org/ or are your running your own one?

I have definitely been using FacilMap with international characters and just tried adding a marker with a Greek name and it worked.

But strangely, the characters in the error message you have sent seem to be encoded in the wrong way. Maybe they are using the wrong charset.

Which are the exact steps how you are trying to add the marker?

**Comment by sysyfo** [comment]
Hey Candid,
how are you? This is Lino from Ecotopia:)
Thanks for your fast reply
I'm using the installation on euchat: [https://facilmap.eauchat.org/](https://facilmap.eauchat.org/r5p0Dn5RnLdn)
I just type a name (in western characters) : it takes me to the locality (in greek) then I go to add to map --> marker (see screnshot)
Thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cdauth** [comment]
I'm not sure what's going on there. I can't reproduce the issue on my server.

It would be good to get in contact with the admin of that instance. I would be curious what database is running there. In case of mysql, the database and all its tables need to have the collation `utf8mb4`.

**Comment by sysyfo** [comment]
Facilmap is installed using docker with the instructions given in facilmap's documentation.
So there is no way that the setup can be different.
But it's possible that you made some changes to the setup, and that the old one had this bug that he solved now? Should we update the version we run on the eauchat server?

**Comment by cdauth** [comment]
Wtf, for some reason the default character set in MariaDB is latin1.

So you need to convert the database and table collations. It seems that the easiest way to do this is to use phpmyadmin, since it provides a way to change the whole database, including all tables and columns:

![image](https://user-images.githubusercontent.com/1801792/80280238-298d5000-8703-11ea-9ee5-3ad9d12443b0.png)

If you don't have phpmyadmin running, this is what a docker-compose configuration could look like:
```
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
        links:
            - db
        restart: on-failure
```

phpmyadmin exposes port 8080.

**Comment by eauchat** [comment]
Hey Candid,

I tried to make the changes to the database that you suggested in your post.
I had to add ports redirection to the phpmyadmin docker-compose config you proposed to get it served on port 8080, but thanks for the config suggestion.

Opening the phpmyadmin page you show, for facilmap database, in collation was written: `latin1_swedish_ci`. I changed it to `utf8mb4_general_ci` ticked the two checkboxes below and hit go.
But I got the following error: 
 > ALTER TABLE `History` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci

and below was written: `MySQL said: #1832 - Cannot change column 'padId': used in a foreign key constraint 'History_ibfk_1'`.

It was pretty fast, but I don't think the database is very big. I don't know if anything happened, but I imagine the conversion was canceled. I didn't do anything after that point, because I know nothing about what I'm doing, and wouldn't want to break more things.

Any idea?

**Comment by cdauth** [comment]
Maybe you could give me temporary access to your phpmyadmin instance and I will manually update the collation?

**Comment by eauchat** [comment]
What do you mean by manually update?
Do you have something in mind that I could do to try to debug this issue?

**Comment by cdauth** [comment]
What I would personally try first is manually change the collation of each column and table inside phpmyadmin

**Comment by eauchat** [comment]
Hey, thank you for your advice and propositions.

I was looking into how to create/modify users/passwords for the database, but it seems not trivial at all, so I gave it up for now.

In the end, I spent an hour modifying collations by hand on the tables and columns. I couldn't convert all columns, the ones like id, key, padId seem to be locked because from what I imagine/understand they are interconnected from one table to another.
I just let those columns as is, since I guess the existing collation shouldn't be an issue (I hope ids only use a basic set of characters).

I don't know if that's what you'd had done, but it seemed to work and now the issue seem to be solved.

Did you investigate why the database is configured by default with `latin1_swedish_ci` collation?
Seems like it would be important for someone installing facilmap with docker that the database is setup right by default.
Maybe it's just a line to add in docker-compose file, I'll investigate that eventually.

**Comment by cdauth** [comment]
Ok, good to know that it worked like this. This is how I would have done it as well.

FYI, creating users in phpmyadmin shouldn't be difficult as long as you use the "User accounts" screen for it.

The reason why it's using that collation is that for some reason that is the default in mariadb. My plan is to update the example docker-compose file to use mysql instead of mariadb, because that one uses a proper default collation and also I've had so many issues with mariadb crashing and data being lost that I'm only using mysql now.

**Comment by eauchat** [comment]
Ok, good to know ;)
I guess then the issue can be closed.
Still I felt like I was in 1980 having to spend hours dealing with charsets issues. Don't really get why we're still at this point. But I'm zero familiar with the sql world. In databases I'm used to, there's not even questions of collation and all those concepts. But that's just different paradigms I guess.

I was just designing these days an app similar to facilmap, if you're interested, I can send you the link. Would be happy to have your feedback on it.

**Comment by cdauth** [comment]
I experienced the same problem now when trying to install FacilMap on Yunohost. I created an issue for it: YunoHost/issues#1777

**Comment by cdauth** [comment]
It is now mentioned in the documentation ([Docker](https://docs.facilmap.org/developers/server/docker.html), [standalone](https://docs.facilmap.org/developers/server/standalone.html)) that the database needs to be created with `utf8mb4`.

I also added some code (https://github.com/FacilMap/facilmap/commit/9a239ae056bb3d242bbff572c9bf096918d19a0a) that explicitly creates tables with `utf8mb4`. Hopefully this will prevent the problem from happening for future installations.
