### ISSUE TITLE
404 - "Not Found"

### ISSUE THREAD

**Issue by pamchus** [FacilMap/facilmap#139]
Hi there.

From few months ago I can't use facilmap.org. I get a 404-NotFound error every time I try to get a route with any settings like "Load route details", "avoid highways", etc.

Thanks!

**Comment by cdauth** [comment]
I noticed this as well. The reason is that OpenRouteService seems to have changed its API completely. When enabling route details or any other of the special routing settings, FacilMap uses OpenRouteService. For simple routing, it uses OSRM, which still works.

I'm currently working on a completely new version of FacilMap. I'm hoping to release it by the end of next week. I will try to fix this in that version.

**Comment by pamchus** [comment]
Oh, really?? That would be great, Candid!

I need to know the elevation profile of motorbike routes, and that is nor possible with Google Maps (that's just for bikes), so I was using your map, but not working anymore.

I wait for it!

Thanks!

**Comment by cdauth** [comment]
You can try out the beta version of FacilMap 3 on [beta.facilmap.org](https://beta.facilmap.org/). Note that it is a temporary instance, any maps that you create or edit there will be removed at some point again. Please report any issues here on GitHub.

**Comment by cdauth** [comment]
FacilMap 3 now runs on [facilmap.org](https://facilmap.org/).
