### ISSUE TITLE
Remove links to Google and Bing maps

### ISSUE THREAD

**Issue by tio-trom** [FacilMap/facilmap#186]
Is there a way to remove these buttons? If so how? I'd like to keep it more private and move away from these pay-for services. Cheers!

**Comment by cdauth** [comment]
The source code for these links can be found in [toolbox.vue](https://github.com/FacilMap/facilmap/blob/master/frontend/src/lib/components/toolbox/toolbox.vue#L66-L68).

To remove the links, remove them from the source code and create a [custom build](https://docs.facilmap.org/developers/development/dev-setup.html).

**Comment by TROMsite** [comment]
I have tested that with a current install at maps.trom.tf to directly edit that file, restart facilmp, but doesn't work. It means that in order for it to work I need to create a custom build and install it again? are the .vue files generating the static files or?

And thanks for the help!

**Comment by cdauth** [comment]
Did you run `yarn build` after editing the files?

**Comment by TROMsite** [comment]
Ah no.I have it installed via Yunohost and I simply edited that file manually to test it out. But I guess it doesn't work like that. Maybe this is too difficult for me. I wanted to be able to edit/remove that, since it is not a free service. But well...will see...maybe I will close this issue for now unless there is an easier way of doing it. Cheers! ;)

**Comment by cdauth** [comment]
I don't have much experience with YunoHost, but I think it's architecture is not really made for custom builds. Anyways once you update to a new version, your changes would be reverted.

I could imagine to include an option to provide custom CSS on a configuration level. Then you could use that to hide the entries from the menu. But I don't know how to do that in a way that would be compatible with the YunoHost architecture.

The reason why these links are even there is that I frequently use them to show information that FacilMap doesn't provide (yet), for example satellite images or in some cases details like opening hours or contact information. I found that providing such external links is a good compromise to allow using such services without actually leaking much data to them.

**Comment by TROMsite** [comment]
A custom CSS box would be fantastic! It will simply overwrite CSS styles already used in the map, right? Should work in theory. I'd love it. You see we provide such services at https://trom.tf/ and we slightly customize them so that they look more or less the same. Not a big deal if we can't do that, but would be nice to have this option for facilmap. We link to the original project (source code) for all of them of course. We add no ads, no trackers, nothing. We call it trade-free https://www.trade-free.org/ :D   

And yes I totally understand that the Bing and Google Satellite have no replacement. I use them too.  My girlfriend is on a hike across the Pyrenees and I was able to upload the GR11 massive trail into our facilmap instance at https://maps.trom.tf - I can track where she is and give her tips at times. All via the facilmap which is fantastic. However I still rely on google satellite to see if I can find some supermarkets nearby so she can buy food, and when they are open.... So my idea was to be able to edit that menu and slightly add a disclaimer for these links to bing and google, saying they are trade-based, meaning you have to trade your data and attention (ads) to these companies in order to use them. So how about you add a warning similar to this as default? So users know these tools are not free, they pay with their data and attention.

You made an amazing project to be honest! Thank you!

**Comment by cdauth** [comment]
The next release will contain two additions:
* Setting the `HIDE_COMMERCIAL_MAP_LINKS=1` environment variable will hide the Google/Bing Maps links from the “Map style” dropdown
* Setting the `CUSTOM_CSS_FILE` environment variable will include the CSS file under the given path.
