### ISSUE TITLE
Marks dont appeare after refreshing colab map

### ISSUE THREAD

**Issue by TobivanW** [FacilMap/facilmap#195]
So I have been playing and I love the colab maps. Great for some cool capture the flag style games.
But I have run into a issue where when I share the map or the readonly link the markers don't show up even though the export does show the features. 

Example:
https://facilmap.org/zeIclkZkBvvC#

**Comment by cdauth** [comment]
Thanks for the report. I think this might be caused by a database upgrade that I did this morning. It seems that there is a [bug](https://jira.mariadb.org/browse/MDEV-26123) in recent versions of MariaDB that is causing this.

I have downgraded the database again, please let me know if the problem still exists.

**Comment by TobivanW** [comment]
There are still issues with the collabmaps the now refuse to load.

**Comment by cdauth** [comment]
It looks like the database has crashed. I'm now migrating from MariaDB back to MySQL, hopefully it will run stable again then.

**Comment by cdauth** [comment]
I migrated the database, it should work again now.

**Comment by TobivanW** [comment]
Thanks, I hosted the docker myself. A lot faster and wont take up bandwith on your server. But I am glad I could download the markers I made.
