### ISSUE TITLE
Add Google Maps and other commercial layers?

### ISSUE THREAD

**Issue by cdauth** [FacilMap/facilmap#4]

**Comment by narcisgarcia** [comment]
-1

**Comment by cdauth** [comment]
@narcisgarcia: Any particular opinion on this?

**Comment by narcisgarcia** [comment]
Copyleft sources are very rich at this time. Better to keep promoting FOSS and copyleft data as good things than giving free advertising and free visitors-tracking to giant corporations.
Facilmap can reach a top quality tool for much people. Let's show how different is this from other software and data models.

**Comment by cdauth** [comment]
The way I thought to implement it was that there would be an additional map style (and possibly an additional search provider? The OpenStreetMap search is just really bad.). For protection of privacy, any Google scripts would only be loaded when this map style is selected (potentially a warning displayed), and it can be disabled in the map settings of collaborative maps (as to not reveal the map ID to Google).

I’m still undecided if it would be needed.

Maybe at least Mapbox Satellite would be nice.

**Comment by narcisgarcia** [comment]
If you implement this kind of "good" sources, please set it off as default setting, and leave user decide if isn't really satisfied with community resources.
Putting those well-known privative resources at same level in an items list implies promoting them as a standard.

I'm contributing with comments and talk about facilmap.org attracted by the project basis at this moment. If it changes direction in this kind of subject, the attention from people like me (pro-copyleft, pro-community) will change too because there are other good FOSS tools to focus.
