### ISSUE TITLE
"Responsive" Marker Shapes and Outlines

### ISSUE THREAD

**Issue by sznattila** [FacilMap/facilmap#78]
Hi,

If it is possible please implement "responsive" marker shapes and outlines too :)
It is really useful that we can create markers and they can change their color and icon based on our conditions. Please if it is possible, implement the same thing for the shape of the markers (including the existing one with the shape of the drop and more. ex: circle, upside-down triangle, square pointing down, pentagon, hexagon, octagon) and their outlines too. (thickness, color, and style).

It would be a great feature and help.
Thank you.

**Comment by cdauth** [comment]
Yes, definitely. I also need this feature.

Also related to #69

**Comment by cdauth** [comment]
I have added a shape property to markers now. For now the only two options are "drop" and "circle". With #69, the possibility to define own shapes will come.

I will think about how useful it would be to have a larger list of shapes defined by default. What are you thoughts on this?

**Comment by sznattila** [comment]
Wow.
Awesome. Thanks. 
For the SVG - it would be useful if we could control the 
- Size
- Color
- Icon
- Shape
- Outline color
- Outline thickness
- Outline style 
- or any character of an uploaded SVG file - maybe it would be possible to have a standardized SVG and the different properties of a custom marker could control the "graphical" elements of an SVG independently.
That would be the best solution I guess...
And create a community library of SVG icons ...

**Comment by cdauth** [comment]
I think having fields to control all those attributes is a bit overkill. The way I imagine it is that you can define your own SVG if you really need custom styles, but I don’t see why for example defining the outline thickness would be needed for a regular use case.

I’m not sure which shapes should be defined by default. I find the drop and the circle useful because they indicate whether a marker is connected to a precise location or to a rough location. I’m not sure what other icons could be useful by default.

**Comment by cdauth** [comment]
There are now 10 different shapes to choose from.

I'm closing this for now, defining custom shapes is tracked as #69.
